name: Deploy to EC2

on:
  push:
    branches: [main] # Trigger the action only on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build # If you have a build step

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd raha-be
            git pull origin main
            npm install
            npm run build  # If needed
            pm2 restart raha-be  # If using PM2
